

networks:
  airline-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  db:
    image: postgres
    container_name: airline-ticket-postgreSQL
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "asa"
    restart: always
    volumes:
      - /var/lib/postgresql/data
    networks:
      airline-network:
        ipv4_address: 172.18.0.3

  airline_app:
    build: .
    container_name: airline-ticket-container
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@172.18.0.3:5432/asa"
    networks:
      airline-network:
        ipv4_address: 172.18.0.2
